### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by sanderdekoning** [cbaker6/CertificateSigningRequest#14] opened 2020-02-29 16:15 UTC
All my CSRs created with this library have an invalid signature. The CSR example that is given in the https://github.com/cbaker6/CertificateSigningRequestSwift_Test readme(copied below) also has an invalid signature. How can I resolve this problem?

`-----BEGIN CERTIFICATE REQUEST----- MIIBFTCBuwIBADBZMQswCQYDVQQGDAJVUzENMAsGA1UECgwEVGVzdDENMAsGA1UE CwwEVGVzdDEsMCoGA1UEAwwjQ2VydGlmaWNhdGVTaWduaW5nUmVxdWVzdFN3aWZ0 IFRlc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATC24iJCr7abrZN0BPaYcM+ cKd/4iXBtHuIM4LzOszsU5pQ9dc9s+srChfWu6m1nCgN48ZHwApTyKV/O0yWWcLA oAAwCgYIKoZIzj0EAwIDSQAwRgIhAPI2FW/izEz8SHAMStctamIzTne+g6AHQWai X0OfkwoBAiEAzXqgv6WVn+VMyxiA25eMc8/Zzrj/mWpew6INRZ1pA1g= -----END CERTIFICATE REQUEST-----`

**Comment by cbaker6** [comment] 2020-03-06 03:01
Did you try running this on a device or just the simulator?

I will attempt to look at this soon, but when I use it on device I don't have issues. For some reason, I would get invalid signature sometimes through the simulator.

**Comment by sanderdekoning** [comment] 2020-03-06 11:07
I tested it on an iPhone XR running iOS 13.3. I generated the private key pair on device using Sec, and then tried creating the CSR which would be invalid. I exported the keys to my Mac to compare the results when using openssl in Terminal to generate the CSR, and then the signature was valid as expected. Ultimately I opted to include openssl in my iOS client and generate the CSR using the openssl library, which gave me the expected results too.

**Comment by sanderdekoning** [comment] 2020-04-27 20:31
@cbaker6 did you resolve this issue in the current master branch?

**Comment by cbaker6** [comment] 2020-04-27 20:37
This issue doesn't show in the many test cases I ran on the master. Can yet set a breakpoint at the line below and let me know what happens when you test the output? https://github.com/cbaker6/CertificateSigningRequestSwift/blob/460e288156285e910af3181e0298a3aadd7f53a9/Example/Tests/Tests.swift#L53

In your personal project, I recommend making sure you setup your keys correctly like the following https://github.com/cbaker6/CertificateSigningRequestSwift/blob/460e288156285e910af3181e0298a3aadd7f53a9/Example/Tests/Tests.swift#L190

**Comment by sanderdekoning** [comment] 2020-04-27 20:49
Thanks bud, I will look at it when I can and let you know. The CSR example in the README still has an invalid signature, see screenshot below.

When you create a CSR on the current master, does it pass on https://redkestrel.co.uk/products/decoder/?

<img width="1288" alt="Screenshot 2020-04-27 at 22 47 01" src="https://user-images.githubusercontent.com/43604043/80419300-2b107100-88d9-11ea-8a6f-42d78c5b6933.png">

**Comment by cbaker6** [comment] 2020-04-27 21:02
I checked in openssl, looks like there may be a padding issue that needs to be fixed. I'll take a look

**Comment by cbaker6** [comment] 2020-04-28 00:21
@sanderdekoning turns out this is not a bug in the framework. When you use keychain you need to be careful when reusing the same "tag" for a key you already created. If the key exists you should reuse it. When you save over it directly, issues occur such as the certificate not being signed by the correct private key.

The other way to deal with this is delete all keys from your apps' keychain. I've added this to the test cases as it fixes the problem when rerunning tests on the same simulator. If you notice in the old test cases, the CSR outputs all pass on the first try. After the first run they all fail because of the issue above. https://github.com/cbaker6/CertificateSigningRequestSwift/blob/2cc68479fba731f2fe22fd06ea637755b01cd2d8/Example/Tests/Tests.swift#L12

**Comment by cbaker6** [comment] 2020-04-28 02:01
Note that deleting the app from the device/simulator doesn't remove them from the Keychain. You have to specifically delete the keys with respect to your app is in the test file above

**Closed** 2020-05-02 16:41 UTC
